/** Metro static requires — generated by scripts/gen-receptive-identify-by-category-assets.js */
export type IdentifyByCategoryId =
  | "animale_domestice"
  | "animale_salbatice"
  | "fructe"
  | "legume"
  | "haine";

export type IdentifyByCategoryItem = { id: string; categoryId: IdentifyByCategoryId; image: number };

const POOL_ANIMALE_DOMESTICE: IdentifyByCategoryItem[] = [
  { id: "caine", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/caine.png") },
  { id: "cal", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/cal.png") },
  { id: "capra", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/capra.png") },
  { id: "curcan", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/curcan.png") },
  { id: "gaina", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/gaina.png") },
  { id: "iepure", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/iepure.png") },
  { id: "magar", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/magar.png") },
  { id: "oaie", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/oaie.png") },
  { id: "pisica", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/pisica.png") },
  { id: "porc", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/porc.png") },
  { id: "rata", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/rata.png") },
  { id: "vaca", categoryId: "animale_domestice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-domestice/vaca.png") },
];

const POOL_ANIMALE_SALBATICE: IdentifyByCategoryItem[] = [
  { id: "cangur", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/cangur.png") },
  { id: "crocodil", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/crocodil.png") },
  { id: "girafa", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/girafa.png") },
  { id: "leu", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/leu.png") },
  { id: "lup", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/lup.png") },
  { id: "maimuta", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/maimuta.png") },
  { id: "tigru", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/tigru.png") },
  { id: "urs", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/urs.png") },
  { id: "vulpe", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/vulpe.png") },
  { id: "zebra", categoryId: "animale_salbatice", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/animale-salbatice/zebra.png") },
];

const POOL_FRUCTE: IdentifyByCategoryItem[] = [
  { id: "ananas", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/ananas.png") },
  { id: "banana", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/banana.png") },
  { id: "capsuna", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/capsuna.png") },
  { id: "cireasa", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/cireasa.png") },
  { id: "kiwi", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/kiwi.png") },
  { id: "lubenita", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/lubenita.png") },
  { id: "mango", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/mango.png") },
  { id: "mar", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/mar.png") },
  { id: "para", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/para.png") },
  { id: "pepene", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/pepene.png") },
  { id: "piersica", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/piersica.png") },
  { id: "portocala", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/portocala.png") },
  { id: "pruna", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/pruna.png") },
  { id: "struguri", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/struguri.png") },
  { id: "zmeura", categoryId: "fructe", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/fructe/zmeura.png") },
];

const POOL_LEGUME: IdentifyByCategoryItem[] = [
  { id: "ardei", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/ardei.png") },
  { id: "broccoli", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/broccoli.png") },
  { id: "cartof", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/cartof.png") },
  { id: "castravete", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/castravete.png") },
  { id: "ceapa", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/ceapa.png") },
  { id: "fasole", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/fasole.png") },
  { id: "mazare", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/mazare.png") },
  { id: "morcov", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/morcov.png") },
  { id: "porumb", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/porumb.png") },
  { id: "rosie", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/rosie.png") },
  { id: "usturoi", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/usturoi.png") },
  { id: "vanata", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/vanata.png") },
  { id: "varza", categoryId: "legume", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/legume/varza.png") },
];

const POOL_HAINE: IdentifyByCategoryItem[] = [
  { id: "haine1", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine1.png") },
  { id: "haine2", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine2.png") },
  { id: "haine3", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine3.png") },
  { id: "haine4", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine4.png") },
  { id: "haine5", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine5.png") },
  { id: "haine6", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine6.png") },
  { id: "haine7", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine7.png") },
  { id: "haine8", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine8.png") },
  { id: "haine9", categoryId: "haine", image: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/imagini/haine/haine9.png") },
];

export const IDENTIFY_BY_CATEGORY_POOLS: Record<IdentifyByCategoryId, IdentifyByCategoryItem[]> = {
  animale_domestice: POOL_ANIMALE_DOMESTICE,
  animale_salbatice: POOL_ANIMALE_SALBATICE,
  fructe: POOL_FRUCTE,
  legume: POOL_LEGUME,
  haine: POOL_HAINE,
};

export function getIdentifyByCategoryPool(categoryId: IdentifyByCategoryId): IdentifyByCategoryItem[] {
  return IDENTIFY_BY_CATEGORY_POOLS[categoryId] ?? [];
}

const PROMPT_AUDIO: Record<IdentifyByCategoryId, number> = {
  animale_domestice: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/audio/arata un animal domestic.mp3"),
  animale_salbatice: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/audio/arata un animal salbatic.mp3"),
  fructe: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/audio/arata un fruct.mp3"),
  legume: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/audio/arata o leguma.mp3"),
  haine: require("../../../assets/programe/limbaj-receptiv/identifica-dupa-categorie/audio/arata o haina.mp3"),
};

export function getIdentifyByCategoryPromptAudio(categoryId: IdentifyByCategoryId): number {
  return PROMPT_AUDIO[categoryId];
}

export function isIdentifyByCategoryId(s: string): s is IdentifyByCategoryId {
  return s in IDENTIFY_BY_CATEGORY_POOLS;
}
