/**
 * Application version for display in the UI.
 * Read from version.json at project root (generated by scripts/generate-version.js).
 * Vercel: v1.0.<count>. Local/default: v1.0.dev.
 */

let version = "1.0.dev";

try {
  const data = require("../../version.json");
  if (data?.version) {
    version = data.version;
  }
} catch {}

export function getAppVersion(): string {
  return `v${version}`;
}
